[package]
name = "constrained-decoding"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
symphony = { path = "../symphony" }
llguidance = { version = "0.6.31", default-features = false, features = ["lark"] }