[package]
name = "constrained-decoding"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet2.workspace = true
inferlet-macros2.workspace = true
futures = "0.3.31"
llguidance = { version = "1.1.1", default-features = false, features = ["lark"] }