[package]
name = "symphony"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
blake3 = "1.5.5"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
wasmtime = "29.0.1"
wasmtime-wasi = "29.0.1"
wit-bindgen = "0.38.0"
zeromq = "0.4.1"
futures = "0.3.31"
parking_lot = "0.12.3"
tungstenite = "0.26.1"
uuid = { version = "1.12.1", features = ["v4"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
rmp-serde = "1.3.0"
serde_bytes = "0.11.15"
