[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1", features = ["rt"] }
wit-bindgen.workspace = true
anyhow = "1.0.95"
symphony= { path = "../symphony" }