
host = "gimlab.org"  # The hostname or IP address to bind to.
port = 9223        # The port to listen on.

controller_host = "192.168.86.20"          # The hostname or IP address of the controller.
controller_port = 9123                 # The port of the controller's WebSocket server.
auth_token = "your-secret-auth-token-here" # The authentication token required by the controller.

model = "qwen-3-0.6b"
device = "cuda:0"
dtype = "bfloat16"
kv_page_size = 16
max_dist_size = 16
max_num_kv_pages = 2048
max_num_embeds = 32
max_num_adapters = 32
max_adapter_rank = 16
