[package]
name = "test-tokenizer"
version = "0.1.0"
edition = "2024"

[dependencies]
fancy-regex = "0.14.0"
rustc-hash = "2.1.1"
bstr = "1.11.3"
base64 = "0.22.1"
kbnf= "0.5.6"
ahash = "0.8.11"
llguidance = "0.6.31"