[package]
name = "image-fetch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet.workspace = true
inferlet-macros.workspace = true
anyhow = "1.0.95"
image = "0.25.5"