[package]
name = "pie"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen.workspace = true
wstd = "0.5.3"
trait-variant = "0.1.2"
wasi = "0.14.2+wasi-0.2.4"
num-traits = "0.2.19"
pie-macros = { path = "../pie-macros" }
anyhow = "1.0.95"