[workspace]
resolver = "2"
members = ["symphony", "symphony-macros", "helloworld", "messaging", "ping", "prefix-sharing", "speculative-decoding", "constrained-decoding", "simple-decoding", "parallel-generation", "function-calling", "helloworld-plain", "openai-compat", "http-server", "text-completion",  "tree-of-thought", "graph-of-thought", "recursion-of-thought", "skeleton-of-thought", "beam-search", "agent-react", "agent-codeact", "agent-swarm", "attention-sink"]

[workspace.dependencies]
wit-bindgen = "0.40.0"

[profile.release]
lto = true
