[workspace]
resolver = "2"
members = ["symphony", "symphony-macros", "helloworld", "messaging", "ping", "prefix-sharing", "speculative-decoding", "simple-decoding", "parallel-generation", "function-calling", "multimodal", "helloworld-plain", "openai-compat", "http-server", "text-completion"]

[workspace.dependencies]
wit-bindgen = "0.40.0"

[profile.release]
lto = true
