[workspace]
resolver = "2"
members = ["typego_s0", "text-completion"]

[workspace.dependencies]
wit-bindgen = "0.46.0"
inferlet = { path = "../inferlet" }
inferlet-macros = { path = "../inferlet-macros" }
[profile.release]
lto = true
