[workspace]
resolver = "2"
members = [ "constrained-decoding",
    "helloworld", "ping", "prefix-sharing", "simple-decoding", "symphony"]

[workspace.dependencies]
wit-bindgen = "0.39.0"

[profile.release]
lto = true
