[workspace]
resolver = "2"
members = ["helloworld", "ping", "prefix-sharing", "speculative-decoding", "simple-decoding", "symphony", "parallel-generation"]



[workspace.dependencies]
wit-bindgen = "0.40.0"

[profile.release]
lto = true
