[workspace]
resolver = "2"
#members = ["helloworld", "messaging", "openai-compat", "constrained-decoding", "kvs", "hierarchical-attention", "windowed-attention", "watermarking", "jacobi-decoding", "prefix-tree", "speculative-decoding", "parallel-generation", "helloworld-plain", "http-server", "text-completion",  "tree-of-thought", "graph-of-thought", "recursion-of-thought", "skeleton-of-thought", "beam-search", "agent-react", "agent-codeact", "agent-swarm", "attention-sink", "bench-spawn-time", "bench-execution-latency", "output-validation", "prefix-caching"]
members = ["text-completion"]

[workspace.dependencies]
wit-bindgen = "0.45.0"
inferlet = { path = "../inferlet" }
inferlet-macros = { path = "../inferlet-macros" }
[profile.release]
lto = true
