[package]
name = "symphony"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen.workspace = true
tokio = { version = "1.44.0", features = ["rt", "sync", "macros"] }
trait-variant = "0.1.2"
tokio-stream = "0.1.17"
