[package]
name = "symphony"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen.workspace = true
tokio = { version = "1", features = ["rt", "sync"] }
trait-variant = "0.1.2"
tokio-stream = "0.1.17"
