[package]
name = "openai-compat"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
symphony = { path = "../symphony" }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9"
rand_distr = "0.5"
anyhow = "1.0"