[package]
name = "test-zmq"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
zeromq = "0.4.1"
uuid = { version = "1.12.1", features = ["serde", "v4"] }
serde = { version = "1.0.217", features = ["derive"] }
rmp-serde = "1.3.0"
rand = "0.8.5"
