[package]
name = "agent-codeact"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inferlet.workspace = true
inferlet-macros.workspace = true
futures = "0.3.31"
pico-args = "0.5.0"
boa_engine = "0.20.0"
